#!/usr/bin/perl

# get global ip
my $global_ip = `curl -s http://ifconfig.me`;

# get local ip
my $local_ip = `ip -4 a show wlp2s0`;

# print ips
print "Global: $global_ip";
print "Local:  $local_ip";
